[
    {
        "Name": "FY22 Template Examples",
        "Sequence": 0,
        "ID": 30203,
        "Title": "Main Menu",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "parent.isIFIT=true;\n\nvar text = \"<p>Select one of the following question types:</p>\";\n\ncreateMenuItem(\"icon-1.jpg\", \"Title, Introductions, Objectives and Summary\", \"Title, Introductions, Objectives and Summary\");\ncreateMenuItem(\"icon-1.jpg\", \"Layouts\", \"Layouts (Text Branching Menu)\");\ncreateMenuItem(\"icon-1.jpg\", \"Question Types\", \"Question Types (Large Branching Menu)\");\ncreateMenuItem(\"icon-1.jpg\", \"Other Frame Types\", \"Other Frame Types (Small Branching Menu)\");\ncreateMenuItem(\"icon-1.jpg\", \"Animate Templates\", \"Animate Templates (Hotspot Branching Menu)\");\ncreateMenuItem(\"icon-1.jpg\", \"ICW3 Samples\", \"ICW3 Samples\");\ncreateMenuItem(\"icon-1.jpg\", \"Features\", \"Features\");\n",
        "Assets": "-1",
        "Template": "BRANCHING_MENU_LARGE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 1,
        "ID": 30204,
        "Title": "Title, Introductions, Objectives and Summary",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text = \"<p>Select one of the following question types:</p>\";\n\ncreateMenuItem(\"icon-1.jpg\", \"Section Title\", \"Section Title\");\ncreateMenuItem(\"icon-1.jpg\", \"Introductions\", \"Lesson Introduction\");\ncreateMenuItem(\"icon-1.jpg\", \"Terminal Learning Objective\", \"Terminal Learning Objective (TLO)\");\ncreateMenuItem(\"icon-1.jpg\", \"Enabling Learning Objective\", \"Enabling Learning Objective (ELO)\");\ncreateMenuItem(\"icon-1.jpg\", \"Summary\", \"Summary\");",
        "Assets": "-1",
        "Template": "BRANCHING_MENU_SMALL"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 2,
        "ID": 29382,
        "Title": "Section Title",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var courseTitle = \"Course Title\";\nvar lessonTitle = \"Lesson Title\";\nvar sectionTitle = \"Section Title\";\nvar distributionStatement = \"<p>DISTRIBUTION D. DISTRIBUTION AUTHORIZED TO DOD AND U.S. DOD CONTRACTORS ONLY; ADMINISTRATIVE OR OPERATIONAL USE, 24 JUL 2018. OTHER REQUESTS FOR THIS DOCUMENT SHALL BE REFERRED TO NAVAL AIR WARFARE CENTER TRAINING SYSTEMS DIVISION, 12211 SCIENCE DRIVE, ORLANDO, FL 32826-3275, READY RELEVANT LEARNING TRAINING SYSTEMS PROGRAM MANAGER.</p><p>DESTRUCTION NOTICE - FOR CLASSIFIED DOCUMENTS, FOLLOW THE PROCEDURES IN DOD 5220.22-M, INDUSTRIAL SECURITY MANUAL, SECTION 11-19 OR DOD 5200.1-R, INFORMATION SECURITY PROGRAM REGULATION, CHAPTER IX. FOR UNCLASSIFIED, LIMITED DOCUMENTS, DESTROY BY ANY METHOD THAT WILL PREVENT DISCLOSURE OF CONTENTS OR RECONSTRUCTION OF THE DOCUMENT.</p>\";\n\nparent.resources = [\n \"Department of Defense Financial Management Regulation (DOD FMR)\",\n \"Joint Travel Regulations - Uniformed Service Members and DOD Civilian Employees\",\n \"Government Travel Charge Card Regulations: Authorized by DoDI 5154.31\",\n \"CCMS Department of Defense User Guide V13.3\",\n \"GTCC Application\"\n]\n\n\nparent.isIFIT=true;",
        "Assets": "-1",
        "Template": "TITLE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 3,
        "ID": 29383,
        "Title": "Lesson Introduction",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "//var graphic = \"AME_1000_M1_L5_4097_Lesson_Intro.jpg\"\nvar text = `<p>In this lesson, you will learn the following:</p>\n<ul>\n<li>[Section 1 Title]</li>\n<li>[Section 2 Title]</li>\n<li>etc.</li>\n</ul>\n<p>[If there is only one section, use the below guidance.]</p>\n<p>In this lesson, you will learn about [Section Title].</p>\n<p>&nbsp;</p>`;",
        "Assets": "-1",
        "Template": "INTRODUCTION"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 4,
        "ID": 29386,
        "Title": "Section Introduction",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = \"Section_Intro.jpg\"\n\nvar text = `<p>In this section, you will learn the following:</p>\n<ul>\n<li>[Main DP/Topic 1]</li>\n<li>[Main DP/Topic 2]</li>\n<li>[Main DP/Topic 3]</li>\n<li>Etc.</li>\n</ul>\n<p>[If there is only one main DP/topic, use the below guidance.]</p>\n<p>In this section, you will learn about [DP/Topic Title].</p>\n<p>[If the section is performance, use the verbiage below.]</p>\n<p>This section covers the following:</p>`;\n",
        "Assets": "-1",
        "Template": "INTRODUCTION"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 5,
        "ID": 29384,
        "Title": "Terminal Learning Objective (TLO)",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var objective1 = \"[Full TLO].\"",
        "Assets": "-1",
        "Template": "TERMINAL_OBJECTIVES"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 6,
        "ID": 29385,
        "Title": "Enabling Learning Objective (ELO)",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var objective1 = \"[Full ELO].\";",
        "Assets": "-1",
        "Template": "ENABLING_OBJECTIVES"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 7,
        "ID": 30144,
        "Title": "Summary",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "//var graphic = \"missing-graphic.jpg\"\nvar text = \"<p>In this lesson, you learned about the various frame types and features.</p>\"",
        "Assets": "-1",
        "Template": "SUMMARY"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 8,
        "ID": 29403,
        "Title": "Layouts (Text Branching Menu)",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text = `<p>The following are the various layout types available:</p>\n<ul>\n<li><a href='javascript:void(0);' id='link1' onclick=\\\"parent.launchBranch('branch_1', this);\\\">Graphic Right Large</a></li>\n<li><a href='javascript:void(0);' id='link2' onclick=\\\"parent.launchBranch('branch_2', this);\\\">Graphic Left Large</a></li>\n<li><a href='javascript:void(0);' id='link3' onclick=\\\"parent.launchBranch('branch_3', this);\\\">Graphic Left with W/C/N</a></li>\n<li><a href='javascript:void(0);' id='link4' onclick=\\\"parent.launchBranch('branch_4', this);\\\">Graphic Top Large</a></li>\n<li><a href='javascript:void(0);' id='link5' onclick=\\\"parent.launchBranch('branch_5', this);\\\">Graphic Bottom Large</a></li>\n<li><a href='javascript:void(0);' id='link6' onclick=\\\"parent.launchBranch('branch_6', this);\\\">Graphic Only</a></li>\n<li><a href='javascript:void(0);' id='link7' onclick=\\\"parent.launchBranch('branch_7', this);\\\">Video Right</a></li>\n<li><a href='javascript:void(0);' id='link8' onclick=\\\"parent.launchBranch('branch_8', this);\\\">Video Only</a></li>\n<li><a href='javascript:void(0);' id='link9' onclick=\\\"parent.launchBranch('branch_9', this);\\\">Text Only</a></li>\n</ul>`;\n\nvar branch_1 = createBranch(\"Graphic Right Large\");\nvar branch_2 = createBranch(\"Graphic Left Large\");\nvar branch_3 = createBranch(\"Graphic Left with W/C/N\");\nvar branch_4 = createBranch(\"Graphic Top Large\");\nvar branch_5 = createBranch(\"Graphic Bottom Large\");\nvar branch_6 = createBranch(\"Graphic Only\");\nvar branch_7 = createBranch(\"Video Right\");\nvar branch_8 = createBranch(\"Video Only\");\nvar branch_9 = createBranch(\"Text Only\");\n\n\n\n\n\n",
        "Assets": "-1",
        "Template": "GRAPHIC_RIGHT"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 9,
        "ID": 29387,
        "Title": "Graphic Right Large",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = \"Left_Right_Large.jpg\";\nvar text = `<p>Aliquam lacinia nec ligula eu egestas:</p>\n<ul>\n<li>Suspendisse iaculis eleifend risus.</li>\n<li>Cras convallis, orci at semper dictum.</li>\n<li>Aliquam lobortis erat in urna luctus.</li>\n</ul>`;\nvar mediaDescription = \"Maecenas nibh nisi.\";",
        "Assets": "-1",
        "Template": "GRAPHIC_RIGHT_LARGE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 10,
        "ID": 29394,
        "Title": "Graphic Left Large",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = \"Left_Right_Large.jpg\";\nvar text = `<p>Aliquam lacinia nec ligula eu egestas:</p>\n<ul>\n<li>Suspendisse iaculis eleifend risus.</li>\n<li>Cras convallis, orci at semper dictum.</li>\n<li>Aliquam lobortis erat in urna luctus.</li>\n</ul>`;\nvar mediaDescription = \"Maecenas nibh nisi.\";",
        "Assets": "-1",
        "Template": "GRAPHIC_LEFT_LARGE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 11,
        "ID": 29395,
        "Title": "Graphic Left with W/C/N",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = \"Left_Right.jpg\";\nvar text = `<p>Aliquam lacinia nec ligula eu egestas:</p>\n<ul>\n<li>Suspendisse iaculis eleifend risus.</li>\n<li>Cras convallis, orci at semper dictum.</li>\n<li>Aliquam lobortis erat in urna luctus.</li>\n</ul>`;\n\nvar mediaDescription = \"Maecenas nibh nisi.\";\n\ncreateWCN(\"Sample warning <hr> If multiple W/C/Ns on a frame, combine into one button and separate each with a horizontal rule.\", \"w\");\ncreateWCN(\"Sample caution\", \"c\");\ncreateWCN(\"Sample note\", \"n\");",
        "Assets": "-1",
        "Template": "GRAPHIC_LEFT"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 12,
        "ID": 29396,
        "Title": "Graphic Top Large",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = `Top_Large.jpg`;\nvar text = \"<p>Phasellus ex erat, maximus vitae tellus sit amet, lacinia rhoncus diam. Nam non congue dolor. Etiam quam felis, dignissim at semper ac, egestas in odio. Morbi in augue id ex dapibus auctor.</p>\"\n\n\nvar mediaDescription = \"Maecenas nibh nisi.\";",
        "Assets": "-1",
        "Template": "GRAPHIC_TOP_LARGE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 13,
        "ID": 29398,
        "Title": "Graphic Bottom Large",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = `Bottom.jpg`;\nvar text = \"<p>Phasellus ex erat, maximus vitae tellus sit amet, lacinia rhoncus diam. Nam non congue dolor. Etiam quam felis, dignissim at semper ac, egestas in odio. Morbi in augue id ex dapibus auctor.<BR><BR>Aliquam dictum molestie sapien eu malesuada. Proin est lectus, eleifend quis bibendum ac, viverra non elit.</p>\"\n\n\nvar mediaDescription = \"Maecenas nibh nisi.\";",
        "Assets": "-1",
        "Template": "GRAPHIC_BOTTOM_LARGE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 14,
        "ID": 29399,
        "Title": "Graphic Only",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = \"Graphic_Full.jpg\"",
        "Assets": "-1",
        "Template": "GRAPHIC_ONLY"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 15,
        "ID": 29400,
        "Title": "Video Right",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var video = \"Inserting a new frame.mp4\"\nvar text = \"<p>Vestibulum fermentum ex eget</p><ul><li>Fusce ultricies libero mi, et consectetur eros sodales auctor.</li><li>Curabitur sed mattis augue, in tempor justo.</li><li>Suspendisse quis sapien metus. Phasellus sagittis mauris eget molestie porta.</li></ul>\";",
        "Assets": "-1,45503",
        "Template": "VIDEO"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 16,
        "ID": 29401,
        "Title": "Video Only",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var video = \"Inserting a new frame.mp4\"\n",
        "Assets": "-1",
        "Template": "VIDEO"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 17,
        "ID": 29402,
        "Title": "Text Only",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text = \"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra vel mauris eget tristique. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam eget dolor sollicitudin, sodales eros ut, ultricies mi. In at ultrices magna. Praesent sollicitudin dignissim tortor, eu consectetur ante feugiat sed. Nunc sem neque, ultricies nec tristique quis, tempus at justo. Ut sit amet augue diam.</p><p>Vestibulum quis nulla felis. In at nibh erat. Sed velit magna, venenatis nec tempor sit amet, interdum quis lorem. In porta elit laoreet volutpat dapibus. Nunc non ligula maximus erat varius blandit. Vestibulum suscipit dui nec magna euismod condimentum ac eget quam. Nullam tristique est vitae diam pharetra, id venenatis est scelerisque. Nunc vel dui in odio volutpat finibus eu sit amet lectus.</p><p>Ut scelerisque eu tellus non sollicitudin. Proin neque augue, aliquet a finibus a, consectetur tempus mauris. Duis in semper felis, ut blandit neque. Maecenas a mi vel neque pulvinar fringilla. Praesent iaculis justo non sollicitudin semper. Curabitur eu nulla quis tellus finibus venenatis et non quam. In eu quam pretium, venenatis tortor maximus, vestibulum lorem. Quisque sit amet vulputate nisl, et volutpat nulla. Ut sed ligula ut nisl cursus auctor sed nec nibh. Praesent pellentesque porttitor odio, sed pretium dui aliquet ac. Cras eget convallis sapien. Curabitur faucibus laoreet sapien ac faucibus. Cras vel sem sem. Aliquam non nibh in tortor placerat rutrum. Duis massa turpis, blandit eget ultricies non, varius ac velit.</p><p>Donec semper enim at condimentum venenatis. Donec mollis ultrices turpis sit amet lacinia. Vivamus sed purus pellentesque, finibus neque in, rhoncus felis. Etiam pharetra sapien nunc, sit amet iaculis sapien feugiat quis. Etiam vulputate libero id lobortis dignissim. Vestibulum tempor rhoncus purus, a mattis leo lacinia id. Proin condimentum ut tortor in tempor. Vestibulum vel dictum odio, gravida iaculis arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec laoreet ullamcorper pretium. Donec interdum nec lorem quis dapibus. Nunc ac purus eros.</p>\";\n\nvar mediaDescription = \" Pellentesque sagittis lacus eget pellentesque.\"",
        "Assets": "-1",
        "Template": "TEXT_ONLY"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 18,
        "ID": 29537,
        "Title": "Question Types (Large Branching Menu)",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text = \"<p>Select one of the following question types:</p>\";\n\ncreateMenuItem(\"icon-1.jpg\", \"Multiple-Choice Text\", \"Multiple-Choice Text\");\ncreateMenuItem(\"icon-1.jpg\", \"Multiple-Choice Text with Supporting Graphic\", \"Multiple-Choice Text with Supporting Graphic\");\ncreateMenuItem(\"icon-1.jpg\", \"Multiple-Select Text\", \"Multiple-Select Text\");\ncreateMenuItem(\"icon-1.jpg\", \"Multiple-Select Graphics\", \"Multiple-Select Graphics\");\ncreateMenuItem(\"icon-1.jpg\", \"Matching Text to Text\", \"Matching Text to Text\");\ncreateMenuItem(\"icon-1.jpg\", \"Matching Text to Graphics\", \"Matching Text to Graphics\");\ncreateMenuItem(\"icon-1.jpg\", \"IFIT Knowledge Check\", \"IFIT Knowledge Check\");",
        "Assets": "-1",
        "Template": "BRANCHING_MENU_LARGE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 19,
        "ID": 29538,
        "Title": "Multiple-Choice Text",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var question = \"Vel quam elementum pulvinar etiam non quam lacus suspendisse. Feugiat nisl pretium fusce id velit ut tortor. Vel orci porta non pulvinar neque laoreet.\";\n\nvar response1= \"Correct Response\";\nvar response1correct = true;\n\nvar response2= \"Incorrect Response\";\nvar response2correct = false;\n\nvar response3= \"Incorrect Response\";\nvar response3correct = false;\n\nvar response4= \"Incorrect Response\";\nvar response4correct = false;\n\ncreateRemediation(\"Swap Graphics\");\n\nvar incorrectFeedback = \"Incorrect Feedback 1.\";\nvar incorrectFeedback2 = \"Incorrect Feedback 2.\";\nvar correctFeedback = \"Correct Feedback.\";",
        "Assets": "-1",
        "Template": "MULTIPLE_SELECT_TEXT"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 20,
        "ID": 29540,
        "Title": "Multiple-Choice Text with Supporting Graphic",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var question = \"The Tool Control Program (TCP) is designed to _____.\";\n\nvar response1= \"Correct Response\";\nvar response1correct = true;\n\nvar response2= \"Incorrect Response\";\nvar response2correct = false;\n\nvar response3= \"Incorrect Response\";\nvar response3correct = false;\n\nvar response4= \"Incorrect Response\";\nvar response4correct = false;\n\nvar supportingGraphic = \"supporting-graphic.jpg\";\nvar supportingGraphic_alt = \"supporting graphic\";\nvar mediaDescription = \"Media Description\";\n\nvar incorrectFeedback = \"Incorrect Feedback 1.\";\nvar incorrectFeedback2 = \"Incorrect Feedback 2.\";\nvar correctFeedback = \"Correct Feedback.\";",
        "Assets": "-1",
        "Template": "MULTIPLE_SELECT_TEXT"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 21,
        "ID": 29584,
        "Title": "Multiple-Select Text",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var question = \"Select the correct response(s).\";\n\nvar response1= \"Distractor\";\nvar response1correct = false;\n\nvar response2= \"Correct response\";\nvar response2correct = true;\n\nvar response3= \"Correct response\";\nvar response3correct = true;\n\nvar response4= \"Distractor\";\nvar response4correct = false;\n\nvar response5= \"Correct response\";\nvar response5correct = true;\n\nvar supportingGraphic = \"missing-graphic.jpg\";\nvar supportingGraphic_alt = \"supporting graphic\";\nvar mediaDescription = \"Media description\";",
        "Assets": "-1",
        "Template": "MULTIPLE_SELECT_TEXT"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 22,
        "ID": 29588,
        "Title": "Multiple-Select Graphics",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var question = \"Select the correct images that are not one of the new Seven Wonders of the World.\";\n\nvar response1= \"mttg-proto_011_a.jpg\";\nvar response1_alt = \"Response 1\";\nvar mediaDescription_1 = \"Media description1\";\nvar response1correct = true;\n\nvar response2= \"mttg-proto_011_b.jpg\";\nvar response2_alt = \"Response 2\";\nvar mediaDescription_2 = \"Media description2\";\nvar response2correct = true;\n\nvar response3= \"mttg-proto_011_c.jpg\";\nvar response3_alt = \"Response 3\";\nvar mediaDescription_3 = \"Media description3\";\nvar response3correct = false;\n\nvar response4= \"mttg-proto_011_d.jpg\";\nvar response4_alt = \"Response 4\";\nvar mediaDescription_4 = \"Media description4\";\nvar response4correct = false;\n\nvar supportingGraphic = \"graphic-medium.jpg\";\nvar mediaDescription = \"Media description\";",
        "Assets": "-1",
        "Template": "MULTIPLE_SELECT_GRAPHICS"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 23,
        "ID": 29542,
        "Title": "Matching Text to Text",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var directions = \"Suspendisse ultrices gravida dictum fusce ut placerat.\";\n\nvar questionText1= \"Question 1\";\nvar answerText1 = \"Answer 1\";\n\nvar questionText2= \"Question 2\";\nvar answerText2 = \"Answer 2\";\n\nvar questionText3= \"Question 3\";\nvar answerText3 = \"Answer 3\";\n\nvar questionText4= \"Question 4\";\nvar answerText4 = \"Answer 4\";\n\nvar supportingGraphic = \"supporting-graphic.jpg\";\nvar mediaDescription = \"Media Description\";\n\ncreateRemediation(\"Swap Graphics\");\n\nvar questionHeader = \"Questions\";\nvar responseHeader = \"Answers\";",
        "Assets": "-1",
        "Template": "MATCHING_TEXT_TO_TEXT"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 24,
        "ID": 29558,
        "Title": "Matching Text to Graphics",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var directions = \"Directions\";\n\nvar questionHeader = \"Header Left\";\nvar responseHeader = \"Header Right\";\n\nvar questionGraphic1 =\"missing-graphic.jpg\";\nvar questionGraphic1_alt = \"Alternate text\";\nvar mediaDescription_1 = \"Media description1\";\nvar answerText1 = \"Answer 1\";\n\nvar questionGraphic2 = \"missing-graphic.jpg\";\nvar questionGraphic2_alt = \"Alternate text\";\nvar mediaDescription_2 = \"Media description2\";\nvar answerText2 = \"Answer 2\";\n\nvar questionGraphic3 = \"missing-graphic.jpg\";\nvar questionGraphic3_alt = \"Alternate text\";\nvar mediaDescription_3 = \"Media description3\";\nvar answerText3 = \"Answer 3\";\n\nvar questionGraphic4 = \"missing-graphic.jpg\";\nvar questionGraphic4_alt = \"Alternate text\";\nvar mediaDescription_4 = \"Media description4\";\nvar answerText4 = \"Answer 4\";\n\nvar supportingGraphic = \"graphic-medium.jpg\";\nvar mediaDescription = \"Media Description\";\n\ncreateRemediation(\"Swap Graphics\");\n",
        "Assets": "-1",
        "Template": "MATCHING_TEXT_TO_GRAPHICS"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 25,
        "ID": 32563,
        "Title": "IFIT Knowledge Check",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = \"missing-graphic.jpg\";\nvar graphic_alt = \"missing graphic\";\nvar question = \"Malesuada nunc vel risus commodo venenatis lectus _____.\";\nvar answer = \"Egestas congue quisque egestas diam.\"",
        "Assets": "48122",
        "Template": "IFIT_KNOWLEDGE_CHECK"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 26,
        "ID": 36787,
        "Title": "Activity Transition (IFIT)",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = `_Activity_Transition.jpg`;\nvar graphic_alt = `Image of destroyer`;\n\n\nvar title = `Instructor-Led Activity`;\nvar subTitle = `Participate in a discussion on ______ [NOTE THIS IMAGE IS FOR SCSTC RATINGS].`;",
        "Assets": "-1,49194",
        "Template": "ACTIVITY_TRANSITION"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 27,
        "ID": 30129,
        "Title": "Other Frame Types (Small Branching Menu)",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text = \"<p>Select one of the following frame types:</p>\";\n\ncreateMenuItem(\"icon-1.jpg\", \"Flash Card\", \"Flash Card\");\ncreateMenuItem(\"icon-1.jpg\", \"Tabs Left\", \"Tabs Left\");\ncreateMenuItem(\"icon-1.jpg\", \"Tabs Top\", \"Tabs Top\");\ncreateMenuItem(\"icon-1.jpg\", \"PDF Viewer\", \"PDF Viewer\");\ncreateMenuItem(\"icon-1.jpg\", \"Transition\", \"Transition\");\ncreateMenuItem(\"icon-1.jpg\", \"Image Viewer\", \"Image Viewer\");\ncreateMenuItem(\"icon-1.jpg\", \"Image Viewer Right\", \"Image Viewer Right\");\ncreateMenuItem(\"icon-1.jpg\", \"Pan Zoom\", \"Pan Zoom\");\ncreateMenuItem(\"icon-1.jpg\", \"Pan Zoom Right\", \"Pan Zoom Right\");\ncreateMenuItem(\"icon-1.jpg\", \"ThreeJS\", \"ThreeJS\");\ncreateMenuItem(\"icon-1.jpg\", \"IMI3 Introduction\", \"IMI3 Introduction\");",
        "Assets": "-1",
        "Template": "BRANCHING_MENU_SMALL"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 28,
        "ID": 30134,
        "Title": "Flash Card",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var title = \"Flashcard Memory Aid\";\n\nvar text = \"Ultricies integer quis auctor elit sed vulputate mi. Nisi vitae suscipit tellus mauris a diam. Porttitor eget dolor morbi non arcu risus. Tempus egestas sed sed risus pretium. \";\n\n\nnewFlashcard(\"Flashcard_Image.jpg\", \"Neque viverra justo nec ultrices dui. Nam at lectus urna duis convallis. Sagittis eu volutpat odio facilisis mauris sit amet massa vitae.\", true);//false shows graphic on back of card\n\nnewFlashcard(\"Flashcard_Image.jpg\",\"Odio euismod lacinia at quis. Tortor pretium viverra suspendisse potenti nullam ac.\", true, \"Media Notes2\");//false shows graphic on back of card\n\nnewFlashcard(\"Flashcard_Image.jpg\",\"Vulputate eu scelerisque felis imperdiet proin.\", true, \"Media Notes3\");//false shows graphic on back of card\n\nnewFlashcard(\"Flashcard_Image.jpg\",\"Bibendum enim facilisis gravida neque convallis a cras semper auctor.\", true, \"Media Notes4\");//false shows graphic on back of card\n",
        "Assets": "-1",
        "Template": "FLASHCARD"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 29,
        "ID": 30135,
        "Title": "Tabs Left",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text = \"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type\";\n\nvar smart_tabs=true;\n\nvar swap_1_image = \"Placeholder_Tab_Graphic_2_968x544_No_Shadow.jpg\";\nvar swap_2_image = \"Placeholder_Tab_Graphic_3_968x544_No_Shadow.jpg\";\n\nnewTab(\"Sample Tab 1\", \n`<p>Nulla posuere sollicitudin aliquam ultrices.</p>\n<p>Click to swap <a href='javascript:void(0);' id='swap_1'>Graphic</a></p>\n<p>Click to swap another <a href='javascript:void(0);' id='swap_2'>Graphic</a></p>`, \ntrue, \n\"Placeholder_Tab_Graphic_968x544_No_Shadow.jpg\", \n\"Media Description Text\");\n\n\nnewTab(\"Sample Tab 2\", \"Vel orci porta non pulvinar neque laoreet. Molestie a iaculis at erat pellentesque adipiscing commodo elit. Phasellus egestas tellus rutrum tellus. Malesuada fames ac turpis egestas maecenas. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa.\", false,\"Placeholder_Tab_Graphic_968x544_No_Shadow.jpg\", \"Media Description Text\");\n\n\nnewTab(\"Sample Tab 3\", \"Morbi tincidunt augue interdum velit.\", false);\n\nnewTab(\"Sample Tab 4\", \"Auctor eu augue ut lectus arcu bibendum at varius.\", false);\n\nnewTab(\"Sample Tab 5\", \"Tempus quam pellentesque nec nam aliquam sem et. Eget nullam non nisi est sit amet.\", false, \"Placeholder_Tab_Graphic_968x544_No_Shadow.jpg\", \"Media Description Text\");\n\nnewTab(\"Sample Tab 6\", \"Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Ultricies mi eget mauris pharetra et ultrices neque ornare. Quis eleifend quam adipiscing vitae proin sagittis.\", false);\n\n\n",
        "Assets": "-1",
        "Template": "TABS_LEFT"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 30,
        "ID": 30136,
        "Title": "Tabs Top",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text = \"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industryâ€™s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type\";\n\nvar smart_tabs=true;\n\nvar swap_1_image = \"Placeholder_Tab_Graphic_2_968x544_No_Shadow.jpg\";\nvar swap_2_image = \"Placeholder_Tab_Graphic_3_968x544_No_Shadow.jpg\";\n\nnewTab(\"Sample Tab 1\",\n`<p>Nulla posuere sollicitudin aliquam ultrices.</p>\n<p>Click to swap <a href=â€™javascript:void(0);â€™ id=â€™swap_1â€™>Graphic</a></p>\n<p>Click to swap another <a href=â€™javascript:void(0);â€™ id=â€™swap_2â€™>Graphic</a></p>`,\ntrue,\n\"Placeholder_Tab_Graphic_968x544_No_Shadow.jpg\",\n\"Media Description Text\");\n\n\nnewTab(\"Sample Tab 2\", \"Vel orci porta non pulvinar neque laoreet. Molestie a iaculis at erat pellentesque adipiscing commodo elit. Phasellus egestas tellus rutrum tellus. Malesuada fames ac turpis egestas maecenas. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa.\", false,\"Placeholder_Tab_Graphic_968x544_No_Shadow.jpg\", \"Media Description Text\");\n\n\nnewTab(\"Sample Tab 3\", \"Morbi tincidunt augue interdum velit.\", false);\n\nnewTab(\"Sample Tab 4\", \"Auctor eu augue ut lectus arcu bibendum at varius.\", false);\n\nnewTab(\"Sample Tab 5\", \"Tempus quam pellentesque nec nam aliquam sem et. Eget nullam non nisi est sit amet.\", false, \"Placeholder_Tab_Graphic_968x544_No_Shadow.jpg\", \"Media Description Text\");\n\nnewTab(\"Sample Tab 6\", \"Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Ultricies mi eget mauris pharetra et ultrices neque ornare. Quis eleifend quam adipiscing vitae proin sagittis.\", false);\n\n\n",
        "Assets": "-1",
        "Template": "TABS_TOP"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 31,
        "ID": 30130,
        "Title": "PDF Viewer",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var file= \"CircuitDrawingsandWiring.pdf\"\n",
        "Assets": "-1,45989",
        "Template": "DOCUMENT_PDF_VIEWER"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 32,
        "ID": 30139,
        "Title": "Transition",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var title = `Main Transition Frame Title`;\nvar subTitle = `Sub Title For Transition`;\nvar graphic = `Title_Screen_Logo.png`;\nvar graphic_alt = `Alt text for graphic`;\n\n\n",
        "Assets": "-1",
        "Template": "TRANSITION"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 33,
        "ID": 30131,
        "Title": "Image Viewer",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = \"missing-graphic.jpg\";\nvar mediaDescription = \"Media description\";",
        "Assets": "-1,45990",
        "Template": "DOCUMENT_IMAGE_VIEWER"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 34,
        "ID": 30132,
        "Title": "Image Viewer Right",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text = \"Sit amet aliquam id diam maecenas. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Eu facilisis sed odio morbi quis commodo. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Orci phasellus egestas tellus rutrum tellus. Hac habitasse platea dictumst quisque sagittis purus sit amet volutpat. Velit scelerisque in dictum non consectetur a erat nam. Fringilla urna porttitor rhoncus dolor.\";\n\nvar graphic = \"missing-graphic.jpg\";\n\nvar mediaDescription = \"Media description\";",
        "Assets": "-1",
        "Template": "DOCUMENT_IMAGE_VIEWER_RIGHT"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 35,
        "ID": 30140,
        "Title": "Pan Zoom",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = \"missing-graphic.png\";\nvar graphic_alt = \"missing graphic\";\n\nvar startScale = .5;\nvar maxScale=4;\nvar minScale=.5;\nvar step=.1;\nvar startX=0;\nvar startY=0;\nvar zoomdelay=120;",
        "Assets": "-1",
        "Template": "PAN_ZOOM_VIEWER"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 36,
        "ID": 30141,
        "Title": "Pan Zoom Right",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = \"missing-graphic.png\";\n\nvar startScale = .5;\nvar maxScale=4;\nvar minScale=.5;\nvar step=.1;\nvar startX=0;\nvar startY=0;\nvar zoomdelay=120;",
        "Assets": "-1",
        "Template": "PAN_ZOOM_VIEWER_RIGHT"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 37,
        "ID": 29609,
        "Title": "ThreeJS",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var modelsource = 'Radial_Pump_Branching.json';\nvar text = \"This is some sample text\";\n",
        "Assets": "47089,47093",
        "Template": "THREEJS"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 38,
        "ID": 36014,
        "Title": "IMI3 Introduction",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": null,
        "Assets": "-1",
        "Template": "IMI3_INTRODUCTION"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 39,
        "ID": 29603,
        "Title": "Animate Templates (Hotspot Branching Menu)",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text = \"<p>Select one of the following Animate-based templates:</p>\";\n\nvar branch_1 = createBranch(\"Drag and Drop - Graphics\");\nvar branch_2 = createBranch(\"Play Animation - Right Large\");\nvar branch_3 = createBranch(\"Rollover Highlights - Fullscreen\");\nvar branch_4 = createBranch(\"Rollover Labels - Callouts\");\nvar branch_5 = createBranch(\"Slideshow Multifunctional - Right Large\");\nvar branch_6 = createBranch(\"Drilldown\");\n",
        "Assets": "46757",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 40,
        "ID": 30936,
        "Title": "Drag and Drop - Graphics",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "createRemediation(\"Remediation Frame\");  //If SDIT\n\n//var correctFeedback = `Enter the correct feedback here`;  //This is optional. Remove comment marks (\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback = `Enter the first incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback2 = `Enter the final incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this",
        "Assets": "46759",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 41,
        "ID": 30937,
        "Title": "Drag and Drop - Labels",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "createRemediation(\"Remediation Frame\");  //If SDIT\n\n//var correctFeedback = `Enter the correct feedback here`;  //This is optional. Remove comment marks (\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback = `Enter the first incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback2 = `Enter the final incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n",
        "Assets": "46760",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 42,
        "ID": 30938,
        "Title": "Drag and Drop - Ordering",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "createRemediation(\"Remediation Frame\");  //If SDIT\n\n//var correctFeedback = `Enter the correct feedback here`;  //This is optional. Remove comment marks (\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback = `Enter the first incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback2 = `Enter the final incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n",
        "Assets": "46761",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 43,
        "ID": 30940,
        "Title": "Drag and Drop - 2 Target - Graphics Only",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "createRemediation(\"Remediation Frame\");  //if SDIT\n\nvar questionText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.`;\n\n\nvar target1Text = `Target 1 Custom Text`;\nvar target2Text = `Target 2 Custom Text`;\n\n//var correctFeedback = `Enter the correct feedback here`;  //This is optional. Remove comment marks (\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback = `Enter the first incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback2 = `Enter the final incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this",
        "Assets": "46762",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 44,
        "ID": 30941,
        "Title": "Drag and Drop - 2 Target - Graphics with Labels",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "createRemediation(\"Remediation Frame\");  //if SDIT\n\nvar questionText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.`;\n\n\nvar target1Text = `Target 1 Custom Text`;\nvar target2Text = `Target 2 Custom Text`;\n\n//var correctFeedback = `Enter the correct feedback here`;  //This is optional. Remove comment marks (\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback = `Enter the first incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback2 = `Enter the final incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this",
        "Assets": "46763",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 45,
        "ID": 30942,
        "Title": "Drag and Drop - 2 Target - Text Only",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "createRemediation(\"Remediation Frame\");  //if SDIT\n\nvar questionText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.`;\n\n\nvar target1Text = `Target 1 Custom Text`;\nvar target2Text = `Target 2 Custom Text`;\n\n//var correctFeedback = `Enter the correct feedback here`;  //This is optional. Remove comment marks (\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback = `Enter the first incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback2 = `Enter the final incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this",
        "Assets": "46764",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 46,
        "ID": 30943,
        "Title": "Drag and Drop - 2 Target - Variety",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "createRemediation(\"Remediation Frame\");  //if SDIT\n\nvar questionText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.`;\n\n\nvar target1Text = `Target 1 Custom Text`;\nvar target2Text = `Target 2 Custom Text`;\n\n//var correctFeedback = `Enter the correct feedback here`;  //This is optional. Remove comment marks (\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback = `Enter the first incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback2 = `Enter the final incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this",
        "Assets": "46765",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 47,
        "ID": 30944,
        "Title": "Drag and Drop - 2 Column Text Only with KC",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "createRemediation(\"Remediation Frame\"); //if SDIT\n\nvar questionText = `This is the test question text entered in MELD.`;\nvar target1Text = `Target 1 Custom Text`;\nvar target2Text = `Target 2 Custom Text`;\n\n//var correctFeedback = `Enter the correct feedback here`;  //This is optional. Remove comment marks (\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback = `Enter the first incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback2 = `Enter the final incorrect attempt text here`; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n",
        "Assets": "46766",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 48,
        "ID": 30945,
        "Title": "Drag and Drop - 3 Column Text Only",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "createRemediation(\"Remediation Frame\");  //if SDIT\n\nvar questionText = `This is the test question text entered in MELD.`;\nvar target1Text = `Target 1 Custom Text`;\nvar target2Text = `Target 2 Custom Text`;\nvar target3Text = `Target 3 Custom Text`;\n\n//var correctFeedback = 'Enter the correct feedback here';  //This is optional. Remove comment marks (\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback = 'Enter the first incorrect attempt text here'; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n//var incorrectFeedback2 = 'Enter the final incorrect attempt text here'; //This is optional. Remove comment marks(\"//\") at the beginning of this line if you want to use this\n",
        "Assets": "46767",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 49,
        "ID": 30946,
        "Title": "Play Animation - Right Large",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var rightLargeText = `<b>Lorem ipsum</b> dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. <br><br>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.`;",
        "Assets": "46768",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 50,
        "ID": 30947,
        "Title": "Play Animation - Fullscreen",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": null,
        "Assets": "46769",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 51,
        "ID": 30948,
        "Title": "Rollover Highlights - Fullscreen",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": null,
        "Assets": "46770",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 52,
        "ID": 30949,
        "Title": "Rollover Highlights - Right Large",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var rightLargeText = `<b>Lorem ipsum</b> dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. <br><br>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.`;",
        "Assets": "46771",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 53,
        "ID": 30950,
        "Title": "Rollover Labels - Callouts",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": null,
        "Assets": "46772",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 54,
        "ID": 30951,
        "Title": "Rollover Labels - Fullscreen",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": null,
        "Assets": "46773",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 55,
        "ID": 30952,
        "Title": "Rollover Labels - Right Large",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var rightLargeText = `<b>Lorem ipsum</b> dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<br><br><b>Lorem ipsum</b> dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`;",
        "Assets": "46774",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 56,
        "ID": 30953,
        "Title": "Slideshow Multifunctional - Right Large",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var frameText1 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.`;\n\nvar frameText2 = `<b>Paragraphs</b> are the building blocks of papers. Many students define paragraphs in terms of length: a paragraph is a group of at least five sentences, a paragraph is half a page long, etc. In reality, though, the unity and coherence of ideas among sentences is what constitutes a paragraph. A paragraph is defined as â€œa group of sentences or a single sentence that forms a unitâ€ (Lunsford and Connors 116).<br><br>Length and appearance do not determine whether a section in a paper is a paragraph. For instance, in some styles of writing, particularly journalistic styles, a paragraph can be just one sentence long. Ultimately, a paragraph is a sentence or group of sentences that support one main idea. In this handout, we will refer to this as the â€œ<i>controlling idea</i>,â€ because it controls what happens in the rest of the paragraph.`;\n\nvar frameText3 = `Test text for frame 3`;\nvar frameText4 = `Test text for frame 4`;\nvar frameText5 = `Test text for frame 5`;\nvar frameText6 = `Test text for frame 6`;\nvar frameText7 = `Test text for frame 7`;\nvar frameText8 = `Test text for frame 8`;\nvar frameText9 = `Test text for frame 9`;",
        "Assets": "46775",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 57,
        "ID": 30954,
        "Title": "Slideshow Multifunctional - Step Table",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": null,
        "Assets": "46776",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 58,
        "ID": 30955,
        "Title": "Slideshow Multifunctional - Variety Fullscreen",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": null,
        "Assets": "46777",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 59,
        "ID": 30956,
        "Title": "Drilldown",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": null,
        "Assets": "46778",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 60,
        "ID": 30128,
        "Title": "ICW3 Samples",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text = \"<p>Select one of the following ICW3 Examples:</p>\";\n\ncreateMenuItem(\"icon-1.jpg\", \"ICW3 Animate Example\", \"ICW3 Animate Example\");\ncreateMenuItem(\"icon-1.jpg\", \"ICW3 Unity Example\", \"ICW3 Unity Example\");",
        "Assets": "-1",
        "Template": "BRANCHING_MENU_SMALL"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 61,
        "ID": 30142,
        "Title": "ICW3 Animate Example",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var datasource = \"HT_1_4_3_4_57532.json\";",
        "Assets": "46808,46809",
        "Template": "ANIMATE"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 62,
        "ID": 29648,
        "Title": "ICW3 Unity Example",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var Introduction = 'Hull Maintenance Technicians (HTs) do the metalwork necessary to maintain all types of shipboard structures, including performing GTAW. The purpose of this exercise is to prepare you to use actual equipment to perform procedures in the lab. This exercise is meant to review and highlight some of the equipment and portions of procedures that you will use in the lab. Note that this exercise is not meant to cover job sheet steps from start to finish. Those steps will be demonstrated by the instructor in the lab. Directions appear at the bottom center of the screen to indicate each appropriate action. The Directions boxes on the screen can be moved if you need to see something on the screen better. The following Help window highlights some actions you can take during the exercise. You can close a menu by selecting the X in the upper-right corner to clearly see what is happening in the exercise. Note that not all buttons or hyperlinks are available on every screen.'\nvar Briefing = 'For welding thin materials, including aluminum, stainless steel, other metals, and alloys, HTs must know how to perform GTAW safely. This type of welding requires precision and skill, since the tungsten needs to avoid touching the workpiece, and materials must not be overheated. During this activity, you will practice starting and stopping the arc and then adding filler, so that when you are in the lab you can focus on the technique required for welding a T-Joint. The torch and materials have been setup except for donning your PPE. Welding PPE will be required for this exercise. Leather welding gloves are used rather than the gauntlet gloves.'\nvar EquipPPE = 'Using the PPE, select the PPE required for GTAW. Then, close the PPE.'\nvar FamiliarizeWithEquipment = 'Select the TIG Torch, the Welding Machine, and the Argon Tank/Regulator to examine the GTAW Equipment.'\nvar CleanTheMetal = 'Using the Toolbox, select the Stain-steel Wire Brush to clean the metal plates.'\nvar EstablishArcAndAssumeTravelPosition = 'Using the Toolbox, select the TIG Torch. It has been equipped with a Tungsten electrode. Then select the plates.'\nvar EstablishArcAndAssumeTravelPositionHint = 'The Argon gas has been set to the correct level and the arc will be established. With the arc established, tilt the torch to about 75 degrees away from the direction you will be adding filler metal.'\nvar AddFillerMetal = 'Select the plate to add filler metal.'\nvar AddFillerMetalHint = 'After the arc has been established, you will notice the base metal will become bright and fluid in the small area of the arc, this is known as the â€œpuddle.â€ This is where you will gently add filler metal.'\nvar TackWeldTheEnd = 'Select the plate to add the filler metal.'\nvar TackWeldTheEndHint = 'You will need to do this quickly but gently, going too slowly can cause the filler to begin to melt in the heat of the arc and ball up before you get to the puddle. If this happens, stop the arc and cut off that balled end.'\nvar BeginWeld = 'Select the bottom metal plate to create your first row of stringer beads.'\nvar BeginWeldHint = 'When you have added filler to the puddle you will need to move the torch forward to about the same place you added the filler, the puddle will move forward and once it becomes bright and fluid again you will add filler again and move. Be careful not to touch the filler to the electrode because this can shock you.'\nvar FinishWeld = 'Select the torch to move it forward and make a new puddle to add filler.'\nvar SecureEquipment = 'Select the torch. Pull the thumb control to lower the amperage to double check that the torch is turned off.'\nvar SecureEquipmentHint = 'The argon gas is then closed off at the regulator and the welding machine is turned off to secure the equipment.'\nvar Debriefing = 'You welded the plates.'\nvar LessonCompletedText = 'Congratulations!'\nvar ppeViolation = 'Equip your PPEs before attempting that action.'\nvar MrcSteps = [\n\t{\n\t\ttype: \"Introduction\",\n\t\ttext: `<div>Hull Maintenance Technicians (HTs) do the metalwork necessary to maintain all types of shipboard structures, including performing GTAW. The purpose of this exercise is to prepare you to use actual equipment to perform procedures in the lab. This exercise is meant to review and highlight some of the equipment and portions of procedures that you will use in the lab. Note that this exercise is not meant to cover job sheet steps from start to finish. Those steps will be demonstrated by the instructor in the lab. Directions appear at the bottom center of the screen to indicate each appropriate action. The Directions boxes on the screen can be moved if you need to see something on the screen better. The following Help window highlights some actions you can take during the exercise. You can close a menu by selecting the X in the upper-right corner to clearly see what is happening in the exercise. Note that not all buttons or hyperlinks are available on every screen.</div>`\n\t},\n\t{\n\t\ttype : \"Step\",\n\t\ttext: `<h3>Step 1</h3>\n\t\t<div>Get familiar with the GTAW equipment.</div>`\n\t},\n\t{\n\t\ttype : \"Step\",\n\t\ttext: `<h3>Step 2</h3>\n\t\t<div>Don the required PPE.</div>`\n\t},\n\t{\n\t\ttype : \"Step\",\n\t\ttext: `<h3>Step 3</h3>\n\t\t<div>Setup for GTAW which includes cleaning the metal surfaces to be welded.</div>`\n\t},\n\t{\n\t\ttype : \"Step\",\n\t\ttext: `<h3>Step 4</h3>\n\t\t<div>Once you have the arc established and the puddle is formed you will need to tilt the torch about 75 degrees away from the direction the filler metal will be added.</div>`\n\t},\n\t{\n\t\ttype : \"Step\",\n\t\ttext: `<h3>Step 5</h3>\n\t\t<div>Hold the filler metal (in the hand that is not holding the torch) like you would hold a pencil. Keep the filler at a flat angle or about 15 degrees from the base metal. Gently touch the end of the filler to the edge of the puddle.</div>`\n\t},\n\t{\n\t\ttype : \"Step\",\n\t\ttext: `<h3>Step 6</h3>\n\t\t<div>Tac weld both ends of the T-Joint.</div>`\n\t},\n\t{\n\t\ttype : \"Step\",\n\t\ttext: `<h3>Step 7</h3>\n\t\t<div>Move the torch forward and add more filler when the puddle forms.</div>`\n\t},\n\t{\n\t\ttype : \"Step\",\n\t\ttext: `<h3>Step 8</h3>\n\t\t<div>Continue adding filler and moving at a consistent speed until the weld is complete.</div>`\n\t},\n\t{\n\t\ttype : \"Step\",\n\t\ttext: `<h3>Step 9</h3>\n\t\t<div>Secure the equipment and tools.</div>`\n\t},\n];",
        "Assets": "46810,46811",
        "Template": "UNITY"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 63,
        "ID": 29610,
        "Title": "Features",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text = \"<p>The following features can be add to most templates:</p>\";\n\ncreateMenuItem(\"icon-1.jpg\", \"Graphic Swapping\", \"Graphic Swapping\");\ncreateMenuItem(\"icon-1.jpg\", \"Warnings, Cautions, and Notes\", \"Warnings, Cautions, and Notes\");\ncreateMenuItem(\"icon-1.jpg\", \"ThreeJS as an asset\", \"ThreeJS as an asset\");\ncreateMenuItem(\"icon-1.jpg\", \"3D Viewer Update\", \"3D Viewer Update\");\ncreateMenuItem(\"icon-1.jpg\", \"3D Prev. upload\", \"3D Prev. upload\");\n\n",
        "Assets": "-1",
        "Template": "BRANCHING_MENU_SMALL"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 64,
        "ID": 29408,
        "Title": "Graphic Swapping",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var graphic = \"Placeholder_Right_Large_1276x805.jpg\"\n\nvar text = \"<ul> <li>Lorem ipsum dolor sit amet</li> <ul> <li>Duis eu risus tincidunt, imperdiet lectus et, aliquam felis <a href='javascript:void(0);' id='swap_1'>cursus libero</a>.</li> <li>Pellentesque ullamcorper nibh eu eros accumsan <a href='javascript:void(0);' id='swap_2'>ultrices lacus blandit</a> vitae.</li> <li>Mauris eleifend, libero sagittis dignissim congue, tortor purus gravida:</li> <ul> <li><a href='javascript:void(0);' id='swap_3'>Maecenas vel turpis</a></li> <li><a href='javascript:void(0);' id='swap_4'>Nulla a libero</a></li> <li><a href='javascript:void(0);' id='swap_5'>Suspendisse a vulputate</a></li> <li><a href='javascript:void(0);' id='swap_6'>Mauris eleifend</a></li> </ul> </ul> </ul>\";\n\nvar swap_1_image = \"swap_1.jpg\";\nvar swap_2_image = \"swap_2.jpg\";\nvar swap_3_image = \"swap_3.jpg\";\nvar swap_4_image = \"swap_4.jpg\";\nvar swap_5_image = \"swap_5.jpg\";\nvar swap_6_image = \"swap_6.jpg\";\n\nvar mediaDescription = \"<p>Media notes go here.</p>\";",
        "Assets": "-1,45507,45508,45509,45510,45511,45513",
        "Template": "GRAPHIC_RIGHT"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 65,
        "ID": 29618,
        "Title": "Warnings, Cautions, and Notes",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text = \"<p>All Warning, Cautions, and Notes must be completed for this frame to be completed.</p>\";\n\n\ncreateWCN(\"Nulla posuere sollicitudin aliquam ultrices. Sit amet nisl purus in mollis.\", \"w\");\ncreateWCN(\"At erat pellentesque adipiscing commodo elit.\", \"c\");\ncreateWCN(\"Viverra vitae congue eu consequat ac felis donec et. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Dui nunc mattis enim ut tellus. Sed turpis tincidunt id aliquet risus feugiat in. \", \"n\");",
        "Assets": "-1",
        "Template": "TEXT_ONLY"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 66,
        "ID": 31357,
        "Title": "ThreeJS as an asset",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var text =\"<p>A ThreeJS asset can rotate, zoom, play an animation and switch camera views. This is integrated, uses the graphic variable and supports multiple cameras and animations.</p><p> If the model has one animation it will loop and autoplay the animation when loads while multiple animations will have a drop down but not autoplay. These cannot be tracked on playing the animations or camera swapping.</P>\";\n\n\n//var graphic=\"helmet.glb\"\n\nvar graphic=\"colorCube_withCameraAnimation3.gltf\"",
        "Assets": "-1,46870,47498",
        "Template": "GRAPHIC_RIGHT"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 67,
        "ID": 31901,
        "Title": "3D Viewer Update",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var modelsource = `GM_1000_M4_L1_S4_10041.json`;\n\nvar text = `<p>A vane pump is a rotary pump that has a circular-shaped or elliptical-shaped interior and flat end plates.</p>\n<p>A slotted rotor is fixed to a shaft in the housing. A series of rectangular plates, or vanes, are set in the slots of the rotor.</p>\n<p>As the rotor turns, centrifugal force causes the outer edge of each vane to slide along the housing as the vanes slide in and out of the rotor slots.</p>\n<p>The cavities formed by the vanes, plates, housing, and rotor enlarge and shrink as the vane assembly rotates.</p>\n<p>Fluid moves from the inlet into the cavities as they enlarge. As the cavities shrink, the fluid flows out of the outlet.</p>\n<p>Most vane pumps are fixed-displacement types. There are variable-displacement vane pumps, but they are rarely used in Navy applications.</p>`;",
        "Assets": "-1,47290,48669",
        "Template": "3D_VIEWER"
    },
    {
        "Name": "FY22 Template Examples",
        "Sequence": 68,
        "ID": 31910,
        "Title": "3D Prev. upload",
        "Graphic": "",
        "Description": "",
        "Keywords": "",
        "Script": "var modelsource = `GM_1000_M4_L1_S4_10041_2.json`;\n\nvar text = `<p>This is like the vane pump on the previous screen but we are using the already uploaded model and using a new JSON file to pull the model into the viewer. You will now see that we have the full model with the expanding slider to expand part of the model so you can see the internal works.</p><p> We only need to upload the unique JSON file for this frame as the model has already been uploaded in a previous frame.</p><p>This reduces the need to keep adding the model into the media folder which reduces the weight of the lesson file size.</p><p><b>NOTE:</b> Preview of this is not available per the frame preview but works on the SCO export.`;",
        "Assets": "-1,47300",
        "Template": "3D_VIEWER"
    }
]